name: publish

on:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to registry
      uses: docker/login-action@v1 
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/amd,linux/arm
        tags: ghcr.io/surface-security/${{ github.event.repository.name }}:${{ github.run_number }},ghcr.io/surface-security/${{ github.event.repository.name }}:latest
